### ISSUE TITLE
implement a LRU to avoid memory issues

### ISSUE THREAD

**Issue by mcollina** [jsumners/node-memcache#1]
See https://github.com/dominictarr/bench-lru for some data, and we should probably benchmark and quantify what is our use case related to eviction.

**Comment by jsumners** [comment]
Help me understand the necessity given the following:

1. This is not meant to be used in production. It is a simple filler to make it easy to get started. I suppose this should be clearer in the documentation. 

2. It is quite aggressive at removing items from the cache. It defaults to using a one second interval timer to purge everything older than the thresholds. And items are removed upon access when their threshold has expired.

**Comment by mcollina** [comment]
1. that was not clear ;)

2. https://github.com/jsumners/node-memcache/blob/master/index.js#L52-L57 this is going to be __very__ costly if there are a lot of keys.

**Comment by jsumners** [comment]
Yes, that is definitely a costly operation and a big reason this is not for production. What would you do to solve it?

**Comment by mcollina** [comment]
I would store entries with an object `{ key, ttl, next }`, and keep them sorted by ttl.

Have a look at https://www.npmjs.com/package/lru_map if you think about going the LRU direction instead.

**Comment by jsumners** [comment]
Your concern has been addressed, my friend. I have swapped out the backing store with `lru_map` and updated the readme to indicate the goal of this module.

**Comment by mcollina** [comment]
❤️
